### ISSUE TITLE
Compatibility with Omeka 2.0?

### ISSUE THREAD

**Issue by CamilleCarette** [Daniel-KM/Omeka-S-module-Group#1]
Hi,

First of all, thank you for creating and maintaining this great module!

I have no problem to report, since everything works perfectly well. I just wanted to ask if it was planned that this module will one day be compatible with Omeka S 2.0? (I know version 2.0 is fairly recent, so it might be too early to ask!)

Thanks a lot,

Camille

**Comment by Daniel-KM** [comment]
It will be upgraded in the next days.
